# Generated by Django 4.2.18 on 2025-01-18 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('CF', 'Ciencia Ficción'), ('TE', 'Terror'), ('SU', 'Suspenso'), ('RO', 'Romántica'), ('CO', 'Comedia')], max_length=2)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AR', 'Arriendo'), ('CO', 'Compra')], max_length=2)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('estado', models.CharField(choices=[('CP', 'Completada'), ('PD', 'Pendiente')], max_length=2)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
