# Generated by Django 4.2.17 on 2025-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('CF', 'Ciencia Ficción'), ('TE', 'Terror'), ('SU', 'Suspenso'), ('RO', 'Romántica'), ('CO', 'Comedia'), ('AC', 'Acción'), ('DR', 'Drama'), ('CR', 'Crimen'), ('AN', 'Animación')], max_length=2),
        ),
    ]
