# Generated by Django 4.2.17 on 2025-01-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_pelicula_descripcion_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
